import Head from "next/head";
import Link from "next/link";
import CopyIcon from "../components/icons/CopyIcon";
import GithubIcon from "../components/icons/GithubIcon";
import LinkedInIcon from "../components/icons/LinkedInIcon";
import styles from "../styles/pages/Contact.module.scss";

export default function Contact() {
    const copyMail = (e) => {
        e.preventDefault();
        navigator.clipboard.writeText("makucode@gmail.com");
    };

    const copyTel = (e) => {
        e.preventDefault();
        navigator.clipboard.writeText("+4917664633526");
    };

    return (
        <div className={styles.Contact}>
            <Head>
                <title>makucode // Contact</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>

            <main className={styles.ContactContainer}>
                <div className={styles.ContactContact}>
                    <div>
                        <span className={styles.Const}>const</span>{" "}
                        <span className={styles.Name}>maku</span>{" "}
                        <span>= &#10100;</span>
                    </div>
                    <p>
                        <span className={styles.Sub}>name:</span> 'Maximilian
                        Friedrich'
                    </p>
                    <Link href="mailto:makucode@gmail.com">
                        <a>
                            <span className={styles.Sub}>email:</span>{" "}
                            'makucode@gmail.com'
                            <CopyIcon click={copyMail} />
                        </a>
                    </Link>
                    <Link href="tel:+4917664633526">
                        <a>
                            <span className={styles.Sub}>tel:</span> '0176 646
                            335 26'
                            <CopyIcon click={copyTel} />
                        </a>
                    </Link>
                    <span>&#10101;</span>
                </div>
                <div className={styles.ContactIcons}>
                    <Link href="https://github.com/makucode" passHref>
                        <a
                            className={styles.ContactIcon}
                            style={{ animationDelay: "0.2s" }}
                        >
                            <GithubIcon />
                        </a>
                    </Link>
                    <Link
                        href="https://www.linkedin.com/in/maximilian-friedrich-266168226/"
                        passHref
                    >
                        <a
                            className={styles.ContactIcon}
                            style={{ animationDelay: "0.4s" }}
                        >
                            <LinkedInIcon />
                        </a>
                    </Link>
                </div>
            </main>
        </div>
    );
}
