import Head from "next/head";

export default function Projects() {
    return (
        <div>
            <Head>
                <title>makucode // Projects</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main></main>

            <footer></footer>
        </div>
    );
}
